export const IP_BACKEND = "http://127.0.0.1:3001"
export const EMAIL_SERVICE_ID = "EMAIL_SERVICE_ID"
export const EMAIL_TAMPLATE_ID = "EMAIL_TAMPLATE_ID"
export const EMAIL_PUBLIC_KEY = "EMAIL_PUBLIC"
